---
- import_tasks: keys/rpm-key.yml
  when: ansible_os_family == "RedHat" or ansible_os_family == "Suse"

- import_tasks: opensource/install-oss.yml
  when: type == "opensource"

- import_tasks: modules/install-njs.yml
  when: modules.njs

- import_tasks: modules/install-perl.yml
  when: modules.perl

- import_tasks: modules/install-geoip.yml
  when: modules.geoip

- import_tasks: modules/install-image-filter.yml
  when: modules.image_filter

- import_tasks: modules/install-rtmp.yml
  when: modules.rtmp

- import_tasks: modules/install-xslt.yml
  when: modules.xslt

- import_tasks: conf/push-config.yml
  when: main_push_enable or http_push_enable or stream_push_enable

- import_tasks: conf/template-config.yml
  when: main_template_enable or http_template_enable or stream_template_enable

- import_tasks: conf/setup-status.yml
  when: status_enable
